import React, { useState } from "react";
import html2pdf from "html2pdf.js";
import { QRCodeCanvas } from "qrcode.react"; // Import QRCodeCanvas
import logo from "../../../assets/SwasthyaSetuLogo.png";
import styles from "./HospitalBookingSlip.module.css";

const HospitalBookingSlip = ({ bookingDetails }) => {
  const [downloading, setDownloading] = useState(false);

  // Default booking details if none provided (for testing purposes)
  const defaultDetails = {
    patientName: "John Doe",
    hospitalName: "Apollo Hospitals",
    specialty: "Cardiology",
    doctorName: "Dr. Priya Sharma",
    appointmentDate: "2025-03-10",
    appointmentTime: "10:00 AM - 10:30 AM",
    bookingId: "APPT123456",
    patientId: "PAT789",
    email: "john.doe@example.com",
  };

  const details = bookingDetails || defaultDetails;
  const currentDate = new Date().toLocaleDateString();

  // QR Code URL (for demo, we'll use a placeholder URL; replace with actual backend URL)
  const qrCodeUrl = `http://localhost:3000/download-booking-slip/${details.bookingId}`; // Example URL

  const handleDownloadPDF = () => {
    setDownloading(true);

    // Generate QR code as an image for the PDF
    const qrCanvas = document.getElementById("qrCodeCanvas");
    const qrCodeDataUrl = qrCanvas.toDataURL("image/png");

    // Create a temporary wrapper for the PDF with a professional layout
    const wrapper = document.createElement("div");
    wrapper.style.padding = "20px";
    wrapper.style.fontFamily = "Arial, sans-serif";
    wrapper.style.color = "#000000";
    wrapper.style.lineHeight = "1.4";
    wrapper.innerHTML = `
      <div style="display: flex; align-items: center; margin-bottom: 20px;">
        <img src="${logo}" alt="Swasthya Setu Logo" style="width: 80px; height: auto; margin-right: 15px;" />
        <h1 style="font-size: 28px; font-weight: bold; color: #000000; margin: 0;">Swasthya Setu</h1>
      </div>
      <div style="margin-bottom: 20px;">
        <p style="font-size: 14px; font-weight: bold; margin: 2px 0;">Patient Name: ${details.patientName}</p>
        <p style="font-size: 14px; font-weight: bold; margin: 2px 0;">Booking ID: ${details.bookingId}</p>
        <p style="font-size: 14px; font-weight: bold; margin: 2px 0;">Patient ID: ${details.patientId}</p>
        <p style="font-size: 14px; font-weight: bold; margin: 2px 0;">Email: ${details.email}</p>
        <p style="font-size: 14px; font-weight: bold; margin: 2px 0;">Date of Issue: ${currentDate}</p>
      </div>
      <hr style="border: 1px solid #000000; margin: 20px 0;" />
      <div style="font-size: 12px;">
        <h2 style="font-size: 18px; font-weight: bold; color: #000000; margin-bottom: 10px;">Appointment Booking Slip</h2>
        <p style="margin-bottom: 10px;">
          <strong>Hospital:</strong> ${details.hospitalName}
        </p>
        <p style="margin-bottom: 10px;">
          <strong>Specialty:</strong> ${details.specialty}
        </p>
        <p style="margin-bottom: 10px;">
          <strong>Doctor:</strong> ${details.doctorName}
        </p>
        <p style="margin-bottom: 10px;">
          <strong>Appointment Date:</strong> ${details.appointmentDate}
        </p>
        <p style="margin-bottom: 10px;">
          <strong>Appointment Time:</strong> ${details.appointmentTime}
        </p>
        <p style="margin-bottom: 10px;">
          <strong>Instructions:</strong> Please arrive 15 minutes early with this slip and any relevant medical records. For cancellations or rescheduling, contact the hospital at least 24 hours prior.
        </p>
        <div style="text-align: center; margin-top: 20px;">
          <img src="${qrCodeDataUrl}" alt="QR Code" style="width: 100px; height: 100px;" />
          <p style="font-size: 10px; margin-top: 5px;">Scan to download this booking slip</p>
        </div>
      </div>
      <hr style="border: 1px solid #000000; margin: 20px 0;" />
      <p style="font-size: 10px; text-align: center; color: #555555;">
        Generated by Swasthya Setu on ${currentDate} | Confidential Appointment Slip
      </p>
    `;

    const opt = {
      margin: 0.5,
      filename: `${details.patientName}_Booking_Slip_${details.bookingId}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
      pagebreak: { mode: ["avoid-all", "css", "legacy"] },
    };

    document.body.appendChild(wrapper);
    html2pdf()
      .from(wrapper)
      .set(opt)
      .save()
      .then(() => {
        document.body.removeChild(wrapper); // Clean up
        setDownloading(false);
      })
      .catch((err) => {
        console.error("PDF generation failed:", err);
        setDownloading(false);
      });
  };

  return (
    <div className={styles.slipContainer}>
      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>Your Appointment Booking Slip</h2>
        <div className={styles.slipDetails}>
          <div className={styles.logoContainer}>
            <img src={logo} alt="Swasthya Setu Logo" className={styles.logo} />
            <h3 className={styles.brandTitle}>Swasthya Setu</h3>
          </div>
          <div className={styles.detailItem}><strong>Patient Name:</strong> {details.patientName}</div>
          <div className={styles.detailItem}><strong>Booking ID:</strong> {details.bookingId}</div>
          <div className={styles.detailItem}><strong>Patient ID:</strong> {details.patientId}</div>
          <div className={styles.detailItem}><strong>Email:</strong> {details.email}</div>
          <div className={styles.detailItem}><strong>Date of Issue:</strong> {currentDate}</div>
          <hr className={styles.divider} />
          <div className={styles.detailItem}><strong>Hospital:</strong> {details.hospitalName}</div>
          <div className={styles.detailItem}><strong>Specialty:</strong> {details.specialty}</div>
          <div className={styles.detailItem}><strong>Doctor:</strong> {details.doctorName}</div>
          <div className={styles.detailItem}><strong>Date:</strong> {details.appointmentDate}</div>
          <div className={styles.detailItem}><strong>Time:</strong> {details.appointmentTime}</div>
          <div className={styles.detailItem}><strong>Instructions:</strong> Arrive 15 minutes early with this slip.</div>
          <div className={styles.qrCodeContainer}>
            <QRCodeCanvas id="qrCodeCanvas" value={qrCodeUrl} size={100} level="H" />
            <p className={styles.qrCodeText}>Scan to download this booking slip</p>
          </div>
        </div>
        <button
          onClick={handleDownloadPDF}
          className={styles.downloadButton}
          disabled={downloading}
        >
          {downloading ? "Generating PDF..." : "Download Booking Slip"}
        </button>
      </div>
    </div>
  );
};

export default HospitalBookingSlip;